#!/bin/sh

# open terminal
alt + shift + Return
	st

# run dmenu
alt + p
        rofi -show drun -theme ~/.config/rofi/app_launcher.rasi

# exit wm
alt + shift + q
        bspc quit

# destroy window
alt + shift + c
        bspc node -c

# program shortcuts
alt + shift + w
        firefox
alt + shift + t
        bspc desktop --focus ^6 && ~/.local/bin/launch_tos
alt + shift + s
        bspc desktop --focus ^4 && signal-desktop --use-tray-icon
alt + shift + l
        libreoffice
alt + shift + r
        st -e ranger
alt + shift + F1
        ~/.local/bin/shutdown

# dmenu scripts
alt + s
        ~/.local/bin/dmenu_ss_region
alt + Print
        ~/.local/bin/dmenu_ss_all
alt + shift + F5
        ~/.local/bin/wallpaper_picker

# window navigation/movement
alt + k
        bspc node -f next.local.window
alt + {h,j,k,l}
        bspc node -z {left -100 0,bottom 0 100,top 0 -100,right 100 0}
alt + {f,g}
        bspc node -t {floating,fullscreen}

# switch workspaces with keyboard shortcuts
alt + {_,shift + }{1-8,0}
        bspc {desktop -f,node -d} '^{1-8,7}'
alt + {_,shift + }{9}
        bspc {desktop -f,node -d} '^{6}'

# resize floating window with mouse
alt + button{1-3}
        ; bspc pointer -g {move,resize_side,resize_corner}
alt + !button{1-3}
        bspc pointer -t %i, %i
alt + @button{1-3}
        bspc pointer -u

# media control, volume, etc
XF86AudioRaiseVolume
        amixer set Master 5%+
XF86AudioLowerVolume
        amixer set Master 5%-
XF86AudioMute
        amixer set Master toggle
