format = "$all"

add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[ ](bold blue)"
error_symbol = "[ ](red)"

[username]
format = "[$user](bold blue)[@](bold blue)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$hostname](bold purple) [in](italic) "
trim_at = "-"
disabled = false

[directory]
format = "[$path](bold cyan) "

[time]
time_format = "%T"
format = " [$time](bold dimmed italic white) "
disabled = true

[package]
disabled = true
