#!/bin/sh

polybar top &

sxhkd &

bspc monitor HDMI-0 -d WWW-II DEV-III MEDIA-IV VMS-V STOCKS-VI
bspc monitor DP-3 -d 󰍺-I

bspc config border_width 2
bspc config window_gap 20
bspc config split_ratio 0.5
